name: 百度极速版
on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
        BAIDU_TASK: ${{ secrets.BAIDU_TASK }}
        BAIDU_CASH: ${{ secrets.BAIDU_CASH }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/muxu-i/Scripts.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install
      - name: '运行 【百度极速】'
        if: env.BAIDU_COOKIE
        run: |
          cd ~/Scripts
          node Task/baidu_speed.js
